export type LabPackage = {
  id: string;
  name: string;
  tagline: string;
  price: string;
  priceFrom?: boolean;
  tests: string[];
  accent: string;
  icon: string;
};

export const packages: LabPackage[] = [
  {
    id: 'vital-check',
    name: 'Vital Check',
    tagline: 'Essential screening',
    price: '480',
    priceFrom: true,
    tests: ['CBC', 'Blood Glucose', 'Urine Routine', 'Blood Group'],
    accent: 'from-emerald-400/20 to-emerald-600/5',
    icon: 'Activity',
  },
  {
    id: 'core-wellness',
    name: 'Core Wellness',
    tagline: 'Comprehensive screening',
    price: '959.2',
    tests: ['CBC', 'Lipid Profile', 'Liver Function', 'Kidney Function', 'Thyroid (TSH)'],
    accent: 'from-sky-400/20 to-sky-600/5',
    icon: 'HeartPulse',
  },
  {
    id: 'diabetes-care',
    name: 'Diabetes Care',
    tagline: 'Diabetes management',
    price: '800',
    priceFrom: true,
    tests: ['Fasting Glucose', 'HbA1c', 'Post Prandial Glucose', 'Urine Glucose'],
    accent: 'from-amber-400/20 to-amber-600/5',
    icon: 'Droplets',
  },
  {
    id: 'heart-guard',
    name: 'Heart Guard',
    tagline: 'Cardiovascular health',
    price: '1200',
    tests: ['Lipid Profile', 'Troponin I', 'CK-MB', 'ECG Markers', 'Homocysteine'],
    accent: 'from-rose-400/20 to-rose-600/5',
    icon: 'Heart',
  },
  {
    id: 'thyroid-balance',
    name: 'Thyroid Balance',
    tagline: 'Thyroid function',
    price: '640',
    priceFrom: true,
    tests: ['TSH', 'T3', 'T4', 'Free T3', 'Free T4'],
    accent: 'from-teal-400/20 to-teal-600/5',
    icon: 'Shield',
  },
  {
    id: 'comprehensive-wellness',
    name: 'Comprehensive Wellness',
    tagline: 'Holistic assessment',
    price: '2000',
    tests: ['60+ Parameters', 'Lipid', 'Liver', 'Kidney', 'Thyroid', 'Vitamins'],
    accent: 'from-indigo-400/20 to-indigo-600/5',
    icon: 'Layers',
  },
  {
    id: 'womens-wellness',
    name: "Women's Wellness",
    tagline: "Women's health",
    price: '1600',
    priceFrom: true,
    tests: ['CBC', 'Iron Studies', 'PCOD Panel', 'Thyroid', 'Vitamin D', 'Hormone Profile'],
    accent: 'from-pink-400/20 to-pink-600/5',
    icon: 'Flower2',
  },
  {
    id: 'senior-care',
    name: 'Senior Care',
    tagline: 'Senior health',
    price: '2400',
    tests: ['Cardiac Risk', 'Bone Density Markers', 'Diabetes', 'Kidney', 'Liver', 'Vitamin B12'],
    accent: 'from-violet-400/20 to-violet-600/5',
    icon: 'Accessibility',
  },
  {
    id: 'anemia-shield',
    name: 'Anemia Shield',
    tagline: 'Anemia screening',
    price: '1200',
    priceFrom: true,
    tests: ['CBC', 'Iron', 'Ferritin', 'TIBC', 'Vitamin B12', 'Folate'],
    accent: 'from-red-400/20 to-red-600/5',
    icon: 'Droplet',
  },
  {
    id: 'arthritis-care',
    name: 'Arthritis Care',
    tagline: 'Arthritis screening',
    price: '1440',
    tests: ['RA Factor', 'CRP', 'ESR', 'Anti-CCP', 'Uric Acid'],
    accent: 'from-orange-400/20 to-orange-600/5',
    icon: 'Bone',
  },
  {
    id: 'pcod-harmony',
    name: 'PCOD Harmony',
    tagline: 'PCOD evaluation',
    price: '2000',
    priceFrom: true,
    tests: ['LH', 'FSH', 'Prolactin', 'Testosterone', 'Insulin', 'Thyroid'],
    accent: 'from-fuchsia-400/20 to-fuchsia-600/5',
    icon: 'Sparkles',
  },
  {
    id: 'vitamin-boost',
    name: 'Vitamin Boost',
    tagline: 'Vitamin levels',
    price: '1600',
    tests: ['Vitamin D', 'Vitamin B12', 'Folate', 'Calcium', 'Magnesium'],
    accent: 'from-yellow-400/20 to-yellow-600/5',
    icon: 'Sun',
  },
  {
    id: 'basic-wellness',
    name: 'Basic Wellness',
    tagline: 'Basic health check',
    price: '799.2',
    priceFrom: true,
    tests: ['CBC', 'Blood Glucose', 'Urine Routine', 'Lipid Profile'],
    accent: 'from-cyan-400/20 to-cyan-600/5',
    icon: 'ClipboardCheck',
  },
  {
    id: 'active-lifestyle',
    name: 'Active Lifestyle',
    tagline: 'Fitness health check',
    price: '1440',
    priceFrom: true,
    tests: ['Lipid Profile', 'Liver Function', 'Kidney Function', 'Electrolytes', 'Vitamin D'],
    accent: 'from-lime-400/20 to-lime-600/5',
    icon: 'Dumbbell',
  },
  {
    id: 'prenatal-care',
    name: 'Prenatal Care',
    tagline: 'Pregnancy health',
    price: '8000',
    tests: ['CBC', 'Blood Group', 'Rh Factor', 'TSH', 'Glucose', 'HIV', 'Hepatitis B', 'Rubella'],
    accent: 'from-rose-300/20 to-rose-500/5',
    icon: 'Baby',
  },
  {
    id: 'cardiac-advance',
    name: 'Cardiac Advance',
    tagline: 'Advanced heart check',
    price: '2800',
    priceFrom: true,
    tests: ['Lipid Profile', 'Troponin', 'BNP', 'Homocysteine', 'Apolipoprotein A/B', 'hs-CRP'],
    accent: 'from-red-500/20 to-rose-700/5',
    icon: 'HeartPulse',
  },
  {
    id: 'liver-health',
    name: 'Liver Health',
    tagline: 'Liver function',
    price: '1600',
    tests: ['SGOT', 'SGPT', 'Bilirubin', 'Alkaline Phosphatase', 'GGT', 'Total Protein'],
    accent: 'from-amber-500/20 to-orange-700/5',
    icon: 'FlaskConical',
  },
  {
    id: 'kidney-care',
    name: 'Kidney Care',
    tagline: 'Kidney health',
    price: '1200',
    priceFrom: true,
    tests: ['Creatinine', 'Urea', 'Uric Acid', 'eGFR', 'Electrolytes', 'Urine Microalbumin'],
    accent: 'from-blue-400/20 to-blue-600/5',
    icon: 'Droplets',
  },
  {
    id: 'allergy-screen',
    name: 'Allergy Screen',
    tagline: 'Allergy test',
    price: '1200',
    tests: ['IgE Total', 'Allergy Panel (30+ Allergens)', 'Eosinophil Count', 'CBC'],
    accent: 'from-teal-300/20 to-teal-600/5',
    icon: 'Wind',
  },
  {
    id: 'cancer-screen',
    name: 'Cancer Screen',
    tagline: 'Cancer screening',
    price: '3200',
    priceFrom: true,
    tests: ['CEA', 'AFP', 'CA 125', 'CA 19.9', 'PSA (Men)', 'Beta HCG'],
    accent: 'from-fuchsia-500/20 to-purple-700/5',
    icon: 'ShieldAlert',
  },
  {
    id: 'metabolic-balance',
    name: 'Metabolic Balance',
    tagline: 'Metabolic health',
    price: '1600',
    tests: ['HbA1c', 'Fasting Insulin', 'Lipid Profile', 'HOMA-IR', 'Vitamin B12'],
    accent: 'from-emerald-500/20 to-teal-700/5',
    icon: 'Gauge',
  },
  {
    id: 'bone-health',
    name: 'Bone Health',
    tagline: 'Bone health check',
    price: '1440',
    priceFrom: true,
    tests: ['Calcium', 'Vitamin D', 'Phosphorus', 'Alkaline Phosphatase', 'Magnesium'],
    accent: 'from-stone-300/20 to-stone-500/5',
    icon: 'Bone',
  },
  {
    id: 'fertility-check',
    name: 'Fertility Check',
    tagline: 'Fertility evaluation',
    price: '2400',
    tests: ['LH', 'FSH', 'Prolactin', 'AMH', 'Estradiol', 'Testosterone', 'Semen Analysis (Men)'],
    accent: 'from-pink-500/20 to-rose-700/5',
    icon: 'Baby',
  },
  {
    id: 'executive-wellness',
    name: 'Executive Wellness',
    tagline: 'Premium health check',
    price: '4000',
    priceFrom: true,
    tests: ['80+ Parameters', 'Cardiac', 'Liver', 'Kidney', 'Thyroid', 'Vitamins', 'Hormones'],
    accent: 'from-sky-500/20 to-indigo-700/5',
    icon: 'Briefcase',
  },
  {
    id: 'immunity-boost',
    name: 'Immunity Boost',
    tagline: 'Immune health',
    price: '2000',
    tests: ['CBC', 'IgG', 'IgM', 'IgA', 'Vitamin D', 'Vitamin C', 'Zinc', 'Selenium'],
    accent: 'from-green-400/20 to-emerald-700/5',
    icon: 'ShieldPlus',
  },
];

export const contact = {
  phone1: '+91 9503832889',
  phone2: '+91 99676 40104',
  whatsapp: '9503832889',
  email: 'report@healthifylab.com',
  locations: ['Mumbai', 'Navi Mumbai', 'Thane', 'Kalyan', 'Pune', 'PCMC'],
};
